version: "3.9"
name: "road_vision__hub"
services:

  hub:
    container_name: hub
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    networks:
      - shared_network


networks:
  shared_network:
    driver:
      bridge
